### ISSUE TITLE
FileNotFoundError: 'VERSION' File Missing Issue

### ISSUE THREAD

**Issue by OD-Ice** [ashvardanian/SimSIMD#150]
Hey，

I encountered a `FileNotFoundError` while trying to install simsimd==4.4.0. The specific error message is as follows:

```
FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'
```

The error occurs when running the `pip` install command, and the traceback is:

```
Traceback (most recent call last):
    File "/usr/local/python-3.10.14/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/usr/local/python-3.10.14/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/python-3.10.14/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-mrslob2o/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
    File "/tmp/pip-build-env-mrslob2o/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-mrslob2o/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
      exec(code, locals())
    File "<string>", line 6, in <module>
  FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'
```

It appears that the build process is unable to locate a file named `VERSION`, which is causing the installation to fail. Could you please assist in resolving this issue? My system uses glibc 2.17 x86_64. Is it possible that the `VERSION` file is missing, or is there an alternative solution?

Thank you very much.

**Comment by ashvardanian** [comment]
Interesting. Can be an environment issue, as the VERSION file is clearly present in the repo. Can you try the same from a new virtual environment.

**Comment by OD-Ice** [comment]
This doesn’t work. The structure of the tar.gz file I downloaded from PyPI is as shown in the picture. Is this normal?
<img width="377" alt="image" src="https://github.com/user-attachments/assets/fdfa4b36-ed1a-4c42-bb74-92b7d6c0709b">
