### ISSUE TITLE
Bug: undefined behavior (shift exponent 150 is too large for 32-bit type 'unsigned int') in `simsimd_uncompress_f16`

### ISSUE THREAD

**Issue by rschu1ze** [ashvardanian/SimSIMD#175]
(sorry, I am intentionally mis-using the "feature" form to open below issue. The "bug" form would not un-grey the "submit a new issue" for me, and I gave up after trying hard for 5 minutes.)

I was enabling the SimSIMD backend for the [usearch](https://github.com/unum-cloud/usearch) submodule in ClickHouse (which is used by our vector search feature), and pushed this [as a PR](https://github.com/ClickHouse/ClickHouse/pull/69387) to GitHub. One of the tests that runs in CI is a SQL fuzzer that runs against an [ubsan](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html) binary. It crashed with this stack:

```
/build/contrib/SimSIMD/include/simsimd/types.h:366:89: runtime error: shift exponent 150 is too large for 32-bit type 'unsigned int'
2024.09.09 23:57:41.500636 [ 727 ] {} <Trace> system.asynchronous_metric_log_sender.DistributedInsertQueue.default: Finished processing `/workspace/db/store/024/024de87c-a871-4266-8243-a16d71de9abf/shard1_replica1/7.bin` (took 1235 ms)
2024.09.09 23:57:41.500790 [ 727 ] {} <Trace> system.asynchronous_metric_log_sender.DistributedInsertQueue.default/Bg: Execution took 1235 ms.
2024.09.09 23:57:42.000178 [ 849 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 1.20 GiB, peak 1.22 GiB, free memory in arenas 0.00 B, will set to 1.19 GiB (RSS), difference: -9.42 MiB
    #0 0x5654e14cc00b in simsimd_uncompress_f16(unsigned short) build_docker/./contrib/SimSIMD/include/simsimd/types.h:366:89
    #1 0x5654e14cc00b in simsimd_l2sq_f16_serial(unsigned short const*, unsigned short const*, unsigned long long, double*) build_docker/./contrib/SimSIMD/include/simsimd/spatial.h:157:1
    #2 0x5654e14d075e in unum::usearch::metric_punned_t::invoke_simsimd(unsigned long, unsigned long) const build_docker/./contrib/usearch/include/usearch/index_plugins.hpp:1799:9
    #3 0x5654e14e0a3a in unum::usearch::metric_punned_t::operator()(char const*, char const*) const build_docker/./contrib/usearch/include/usearch/index_plugins.hpp:1604:16
    #4 0x5654e14e0a3a in unum::usearch::index_dense_gt<unsigned long, unsigned int>::metric_proxy_t::f(char const*, char const*) const build_docker/./contrib/usearch/include/usearch/index_dense.hpp:439:87
    #5 0x5654e14e0a3a in unum::usearch::index_dense_gt<unsigned long, unsigned int>::metric_proxy_t::operator()(char const*, unum::usearch::index_gt<float, unsigned long, unsigned int, unum::usearch::aligned_allocator_gt<char, 64ul>, unum::usearch::memory_mapping_allocator_gt<64ul>>::member_iterator_gt<unum::usearch::member_cref_gt<unsigned long>, unum::usearch::index_gt<float, unsigned long, unsigned int, unum::usearch::aligned_allocator_gt<char, 64ul>, unum::
    > usearch::memory_mapping_allocator_gt<64ul>> const>) const build_docker/./contrib/usearch/include/usearch/index_dense.hpp:430:101
    #6 0x5654e14df0c5 in float unum::usearch::index_gt<float, unsigned long, unsigned int, unum::usearch::aligned_allocator_gt<char, 64ul>, unum::usearch::memory_mapping_allocator_gt<64ul>>::context_t::measure<char const*, unum::usearch::index_dense_gt<unsigned long, unsigned int>::metric_proxy_t&, unum::usearch::index_gt<float, unsigned long, unsigned int, unum::usearch::aligned_allocator_gt<char, 64ul>, unum::usearch::memory_mapping_allocator_gt<64ul>>::
    > member_iterator_gt<unum::usearch::member_cref_gt<unsigned long>, unum::usearch::index_gt<float, unsigned long, unsigned int, unum::usearch::aligned_allocator_gt<char, 64ul>, unum::usearch::memory_mapping_allocator_gt<64ul>> const>>(char const* const&, unum::usearch::index_gt<float, unsigned long, unsigned int, unum::usearch::aligned_allocator_gt<char, 64ul>, unum::usearch::memory_mapping_allocator_gt<64ul>>::member_iterator_gt<unum::usearch::
    > member_cref_gt<unsigned long>, unum::usearch::index_gt<float, unsigned long, unsigned int, unum::usearch::aligned_allocator_gt<char, 64ul>, unum::usearch::memory_mapping_allocator_gt<64ul>> const> const&, unum::usearch::index_dense_gt<unsigned long, unsigned int>::metric_proxy_t&) build_docker/./contrib/usearch/include/usearch/index.hpp:2207:20
    #7 0x5654e14df0c5 in unsigned int unum::usearch::index_gt<float, unsigned long, unsigned int, unum::usearch::aligned_allocator_gt<char, 64ul>, unum::usearch::memory_mapping_allocator_gt<64ul>>::search_for_one_<char const*&, unum::usearch::index_dense_gt<unsigned long, unsigned int>::metric_proxy_t&, unum::usearch::dummy_prefetch_t&>(char const*&, unum::usearch::index_dense_gt<unsigned long, unsigned int>::metric_proxy_t&, unum::usearch::dummy_prefetch_t&, unsigned
    > int, short, short, unum::usearch::index_gt<float, unsigned long, unsigned int, unum::usearch::aligned_allocator_gt<char, 64ul>, unum::usearch::memory_mapping_allocator_gt<64ul>>::context_t&) const build_docker/./contrib/usearch/include/usearch/index.hpp:3889:43
    #8 0x5654e14de748 in unum::usearch::index_gt<float, unsigned long, unsigned int, unum::usearch::aligned_allocator_gt<char, 64ul>, unum::usearch::memory_mapping_allocator_gt<64ul>>::add_result_t unum::usearch::index_gt<float, unsigned long, unsigned int, unum::usearch::aligned_allocator_gt<char, 64ul>, unum::usearch::memory_mapping_allocator_gt<64ul>>::add<char const*&, unum::usearch::index_dense_gt<unsigned long, unsigned int>::metric_proxy_t&, unum::usearch::
    > index_gt<float, unsigned long, unsigned int, unum::usearch::aligned_allocator_gt<char, 64ul>, unum::usearch::memory_mapping_allocator_gt<64ul>>::add_result_t unum::usearch::index_dense_gt<unsigned long, unsigned int>::add_<float>(unsigned long, float const*, unsigned long, bool, bool (* const&)(char const*, unsigned long, char*))::'lambda'(unum::usearch::member_ref_gt<unsigned long>)&, unum::usearch::dummy_prefetch_t>(unsigned long, float&&, unum::usearch::
    > index_dense_gt<unsigned long, unsigned int>::metric_proxy_t&, unum::usearch::index_update_config_t, unum::usearch::index_gt<float, unsigned long, unsigned int, unum::usearch::aligned_allocator_gt<char, 64ul>, unum::usearch::memory_mapping_allocator_gt<64ul>>::add_result_t unum::usearch::index_dense_gt<unsigned long, unsigned int>::add_<float>(unsigned long, float const*, unsigned long, bool, bool (* const&)(char const*, unsigned long, char*))::'lambda'(unum::
    > usearch::member_ref_gt<unsigned long>)&, unum::usearch::dummy_prefetch_t&&) build_docker/./contrib/usearch/include/usearch/index.hpp:2761:42
    #9 0x5654e14dda8d in unum::usearch::index_gt<float, unsigned long, unsigned int, unum::usearch::aligned_allocator_gt<char, 64ul>, unum::usearch::memory_mapping_allocator_gt<64ul>>::add_result_t unum::usearch::index_dense_gt<unsigned long, unsigned int>::add_<float>(unsigned long, float const*, unsigned long, bool, bool (* const&)(char const*, unsigned long, char*)) build_docker/./contrib/usearch/include/usearch/index_dense.hpp:2040:16
    #10 0x5654e14c5e76 in unum::usearch::index_dense_gt<unsigned long, unsigned int>::add(unsigned long, float const*, unsigned long, bool) build_docker/./contrib/usearch/include/usearch/index_dense.hpp:773:136
    #11 0x5654e14c5e76 in void DB::(anonymous namespace)::updateImpl<DB::ColumnVector<float>>(DB::ColumnArray const*, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 63ul, 64ul> const&, std::__1::shared_ptr<DB::USearchIndexWithSerialization>&, unsigned long, unsigned long) build_docker/./src/Storages/MergeTree/MergeTreeIndexVectorSimilarity.cpp:278:34
    #12 0x5654e14c5e76 in DB::MergeTreeIndexAggregatorVectorSimilarity::update(DB::Block const&, unsigned long*, unsigned long) build_docker/./src/Storages/MergeTree/MergeTreeIndexVectorSimilarity.cpp:352:9
    #13 0x5654e13bccd4 in DB::MergeTreeDataPartWriterOnDisk::calculateAndSerializeSkipIndices(DB::Block const&, std::__1::vector<DB::Granule, std::__1::allocator<DB::Granule>> const&) build_docker/./src/Storages/MergeTree/MergeTreeDataPartWriterOnDisk.cpp:416:42
    #14 0x5654e13aaa5f in DB::MergeTreeDataPartWriterCompact::writeDataBlockPrimaryIndexAndSkipIndices(DB::Block const&, std::__1::vector<DB::Granule, std::__1::allocator<DB::Granule>> const&) build_docker/./src/Storages/MergeTree/MergeTreeDataPartWriterCompact.cpp:221:5
    #15 0x5654e13a9ace in DB::MergeTreeDataPartWriterCompact::write(DB::Block const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 63ul, 64ul> const*) build_docker/./src/Storages/MergeTree/MergeTreeDataPartWriterCompact.cpp:204:9
    #16 0x5654e15cf800 in DB::MergedBlockOutputStream::writeImpl(DB::Block const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 63ul, 64ul> const*) build_docker/./src/Storages/MergeTree/MergedBlockOutputStream.cpp:358:13
    #17 0x5654e1418059 in DB::MergeTreeDataWriter::writeTempPartImpl(DB::BlockWithPartition&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>, long, bool) build_docker/./src/Storages/MergeTree/MergeTreeDataWriter.cpp:639:10
    #18 0x5654e1413bf3 in DB::MergeTreeDataWriter::writeTempPart(DB::BlockWithPartition&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>) build_docker/./src/Storages/MergeTree/MergeTreeDataWriter.cpp:421:12
    #19 0x5654e18378b9 in DB::MergeTreeSink::consume(DB::Chunk&) build_docker/./src/Storages/MergeTree/MergeTreeSink.cpp:118:40
    #20 0x5654e25d90a6 in DB::SinkToStorage::onConsume(DB::Chunk) build_docker/./src/Processors/Sinks/SinkToStorage.cpp:18:5
    #21 0x5654e242007d in DB::ExceptionKeepingTransform::work()::$_1::operator()() const build_docker/./src/Processors/Transforms/ExceptionKeepingTransform.cpp:1502024.09.09 23:57:42.452754 [ 164 ] {} <Trace> BaseDaemon: Received signal -3
:51
    #22 0x5654e242007d in decltype(std::declval<DB::ExceptionKeepingTransform::work()::$_1&>()()) std::__1::__invoke[abi:v15007]<DB::ExceptionKeepingTransform::work()::$_1&>(DB::ExceptionKeepingTransform::work()::$_1&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #23 0x5654e242007d in void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::ExceptionKeepingTransform::work()::$_1&>(DB::ExceptionKeepingTransform::work()::$_1&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #24 0x5654e242007d in std::__1::__function::__default_alloc_func<DB::ExceptionKeepingTransform::work()::$_1, void ()>::operator()[abi:v15007]() build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #25 0x5654e242007d in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::ExceptionKeepingTransform::work()::$_1, void ()>>(std::__1::__function::__policy_storage const*) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #26 0x5654e241fc2a in std::__1::__function::__policy_func<void ()>::operator()[abi:v15007]() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #27 0x5654e241fc2a in std::__1::function<void ()>::operator()() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1197:12
    #28 0x5654e241fc2a in DB::runStep(std::__1::function<void ()>, DB::ThreadStatus*, std::__1::atomic<unsigned long>*) build_docker/./src/Processors/Transforms/ExceptionKeepingTransform.cpp:114:9
    #29 0x5654e241e86b in DB::ExceptionKeepingTransform::work() build_docker/./src/Processors/Transforms/ExceptionKeepingTransform.cpp:150:34
    #30 0x5654e1ddaf5f in DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:47:26
    #31 0x5654e1ddaf5f in DB::ExecutionThreadContext::executeTask() build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:96:9
    #32 0x5654e1dc76e2 in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) build_docker/./src/Processors/Executors/PipelineExecutor.cpp:283:26
    #33 0x5654e1dc6da2 in DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) build_docker/./src/Processors/Executors/PipelineExecutor.cpp:157:5
    #34 0x5654e1c7f0c2 in _ZZN2DB10TCPHandler18processInsertQueryEvENK3$_0clINS_23PushingPipelineExecutorEEEDaRT_NS_5BlockE build_docker/./src/Server/TCPHandler.cpp:988:22
    #35 0x5654e1c7f0c2 in DB::TCPHandler::processInsertQuery() build_docker/./src/Server/TCPHandler.cpp:1056:9
    #36 0x5654e1c685f1 in DB::TCPHandler::runImpl() build_docker/./src/Server/TCPHandler.cpp:581:17
    #37 0x5654e1c9e3f5 in DB::TCPHandler::run() build_docker/./src/Server/TCPHandler.cpp:2484:9
    #38 0x5654e573f677 in Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3
    #39 0x5654e57407b1 in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:38
    #40 0x5654e56931a0 in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:205:14
    #41 0x5654e568e16e in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #42 0x7efe9a19cac2 in start_thread nptl/pthread_create.c:442:8
    #43 0x7efe9a22e84f  misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /build/contrib/SimSIMD/include/simsimd/types.h:366:89
```

This is based on
- an unmodified usearch 2.16.1 (using static i.e. non-runtime dispatch),
- an unmodified SimSIMD 5.0.0.

I was unfortunately not able to reproduce the problem locally (ClickHouse generally prints executed SQL statements into its log and in this case it is an INSERT statement that populates the usearch HNSW index. Unfortunately, the exact values that were inserted were not logged :-( ).

The problem is here:

```cpp
/**
 *  @brief  For compilers that don't natively support the `_Float16` type,
 *          upcasts contents into a more conventional `float`.
 *
 *  @warning  This function won't handle boundary conditions well.
 *
 *  https://stackoverflow.com/a/60047308
 *  https://gist.github.com/milhidaka/95863906fe828198f47991c813dbe233
 *  https://github.com/OpenCyphal/libcanard/blob/636795f4bc395f56af8d2c61d3757b5e762bb9e5/canard.c#L811-L834
 */
SIMSIMD_PUBLIC simsimd_f32_t simsimd_uncompress_f16(unsigned short x) {
    union float_or_unsigned_int_t {
        float f;
        unsigned int i;
    };
    unsigned int exponent = (x & 0x7C00) >> 10;
    unsigned int mantissa = (x & 0x03FF) << 13;
    union float_or_unsigned_int_t mantissa_union;
    mantissa_union.f = (float)mantissa;
    unsigned int v = (mantissa_union.i) >> 23;
    union float_or_unsigned_int_t result_union;
    result_union.i = (x & 0x8000) << 16 | (exponent != 0) * ((exponent + 112) << 23 | mantissa) |
                     ((exponent == 0) & (mantissa != 0)) * ((v - 37) << 23 | ((mantissa << (150 - v)) & 0x007FE000));
    return result_union.f;
}
```

If `v` is too small, `mantissa << (150 - v)` shifts too many bits (at most 32 are legal).

Not directly related to the issue but doxygen "For compilers that don't natively support the `_Float16` type" made me wonder why the code is executed at all (it is a fallback for old compilers) ... after all I am using a recent Clang compiler. I'll check why `SIMSIMD_NATIVE_F16` was not set.

### Can you contribute to the implementation?

- [X] I can contribute

### Is your feature request specific to a certain interface?

C++ bindings

### Contact Details

robert@clickhouse.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
In newer versions, not yet merged in USearch, I pass arguments by pointer, which helps avoid implicit casts. That may be the issue here. Any chance you can try them? The `main-dev` branch of USearch should br compatible.

**Comment by rschu1ze** [comment]
Beautiful, `main-dev` doesn't crash anymore 😄
