### ISSUE TITLE
Will not work in a Vercel instance

### ISSUE THREAD

**Issue by FlipFloop** [ashvardanian/SimSIMD#60]
Both for Node 18 and Node 20:

```
[14:23:34.076] .../usearch@2.8.15/node_modules/usearch install: ../simsimd/include/simsimd/types.h:27: warning: "SIMSIMD_TARGET_ARM_NEON" redefined
[14:23:34.076] .../usearch@2.8.15/node_modules/usearch install:    27 | #define SIMSIMD_TARGET_ARM_NEON 0
[14:23:34.076] .../usearch@2.8.15/node_modules/usearch install:       | 
[14:23:34.077] .../usearch@2.8.15/node_modules/usearch install: <command-line>: note: this is the location of the previous definition
[14:23:34.077] .../usearch@2.8.15/node_modules/usearch install: In file included from ../simsimd/include/simsimd/binary.h:23,
[14:23:34.077] .../usearch@2.8.15/node_modules/usearch install:                  from ../simsimd/include/simsimd/simsimd.h:17,
[14:23:34.077] .../usearch@2.8.15/node_modules/usearch install:                  from ../include/usearch/index_plugins.hpp:68,
[14:23:34.077] .../usearch@2.8.15/node_modules/usearch install:                  from ../include/usearch/index_dense.hpp:10,
[14:23:34.078] .../usearch@2.8.15/node_modules/usearch install:                  from ../javascript/lib.cpp:18:
[14:23:34.078] .../usearch@2.8.15/node_modules/usearch install: ../simsimd/include/simsimd/types.h:36: warning: "SIMSIMD_TARGET_ARM_SVE" redefined
[14:23:34.078] .../usearch@2.8.15/node_modules/usearch install:    36 | #define SIMSIMD_TARGET_ARM_SVE 0
[14:23:34.078] .../usearch@2.8.15/node_modules/usearch install:       | 
[14:23:34.078] .../usearch@2.8.15/node_modules/usearch install: <command-line>: note: this is the location of the previous definition
[14:23:35.137] .../usearch@2.8.15/node_modules/usearch install: In file included from ../simsimd/include/simsimd/simsimd.h:18,
[14:23:35.138] .../usearch@2.8.15/node_modules/usearch install:                  from ../include/usearch/index_plugins.hpp:68,
[14:23:35.138] .../usearch@2.8.15/node_modules/usearch install:                  from ../include/usearch/index_dense.hpp:10,
[14:23:35.138] .../usearch@2.8.15/node_modules/usearch install:                  from ../javascript/lib.cpp:18:
[14:23:35.138] .../usearch@2.8.15/node_modules/usearch install: ../simsimd/include/simsimd/probability.h:457:8: error: '__m512h' does not name a type; did you mean '__m512i'?
[14:23:35.138] .../usearch@2.8.15/node_modules/usearch install:   457 | inline __m512h
[14:23:35.138] .../usearch@2.8.15/node_modules/usearch install:       |        ^~~~~~~
[14:23:35.138] .../usearch@2.8.15/node_modules/usearch install:       |        __m512i
[14:23:35.138] .../usearch@2.8.15/node_modules/usearch install: ../simsimd/include/simsimd/probability.h:477:1: error: attribute 'avx512fp16' argument 'target' is unknown
[14:23:35.139] .../usearch@2.8.15/node_modules/usearch install:   477 | simsimd_avx512_f16_kl(simsimd_f16_t const* a, simsimd_f16_t const* b, simsimd_size_t n) {
[14:23:35.139] .../usearch@2.8.15/node_modules/usearch install:       | ^~~~~~~~~~~~~~~~~~~~~
```

Vercel error log:
```
500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
ID: cle1:cle1::sw2js-1705001182897-78fa89a33f7c
```

```
19:26:23 [ERROR] Error: No native build was found for platform=linux arch=x64 runtime=node abi=115 uv=1 libc=glibc node=20.10.0
    loaded from: /var/task/node_modules/.pnpm/simsimd@3.6.3/node_modules/simsimd

    at load.resolve.load.path (/var/task/node_modules/.pnpm/node-gyp-build@4.8.0/node_modules/node-gyp-build/node-gyp-build.js:60:9)
    at load (/var/task/node_modules/.pnpm/node-gyp-build@4.8.0/node_modules/node-gyp-build/node-gyp-build.js:22:30)
    at Object.<anonymous> (/var/task/node_modules/.pnpm/simsimd@3.6.3/node_modules/simsimd/javascript/simsimd.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at r.<computed>.e._load (/var/task/___vc/__launcher/bridge-server-72TT5FOD.js:1:1574)
    at cjsLoader (node:internal/modules/esm/translators:345:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
```

**Comment by ashvardanian** [comment]
Hi, @FlipFloop! It should work if you upgrade the compiler. If you are on Linux, I suggest GCC 12 or newer. Can you please try again?

**Comment by FlipFloop** [comment]
My local machine isn't the problem. I am trying to make this work on an [Astro](https://astro.build/) site in Vercel. Like so:

```

import {
  runPerformanceTest,
  normalizeColors,
  generateRandom1DArray,
  type PerformanceTestResult,
} from "~/utils/performanceTime";

import { sqeuclidean } from "simsimd";

const numIterations = 1000;
const small_size = 5;
const vectorA = generateRandom1DArray(small_size);
const vectorB = generateRandom1DArray(small_size);

const vectorA_F32Arr = new Float32Array(vectorA);
const vectorB_F32Arr = new Float32Array(vectorB);

const medium_size = 500;
const vectorC = generateRandom1DArray(medium_size);
const vectorD = generateRandom1DArray(medium_size);

const vectorC_F32Arr = new Float32Array(vectorC);
const vectorD_F32Arr = new Float32Array(vectorD);

const long_size = 5000;
const vectorE = generateRandom1DArray(long_size);
const vectorF = generateRandom1DArray(long_size);

const vectorE_F32Arr = new Float32Array(vectorE);
const vectorF_F32Arr = new Float32Array(vectorF);

const runPerformanceTests = (
  algorithm: (a: any, b: any) => number,
  vector1: number[] | Float32Array,
  vector2: number[] | Float32Array,
  iterations: number,
): PerformanceTestResult => {
  let totalTime = 0;
  let totalResult = 0;

  for (let i = 0; i < iterations; i++) {
    const { result, time } = runPerformanceTest(algorithm, vector1, vector2);
    totalResult += result;
    totalTime += time;
  }

  const averageTime = totalTime / iterations;
  const averageResult = totalResult / iterations;

  return { result: averageResult, time: averageTime };
};

const euclideanDistance = (a: number[], b: number[]) => {
  return Math.hypot(...Object.keys(a).map((k: any) => b[k] - a[k])) ** 2;
};

const { result: avgResSimSmall, time: avgTimeSimSmall } = runPerformanceTests(
  sqeuclidean,
  vectorA_F32Arr,
  vectorB_F32Arr,
  numIterations,
);

const { result: avgResMathSmall, time: avgTimeMathSmall } = runPerformanceTests(
  euclideanDistance,
  vectorA,
  vectorB,
  numIterations,
);

const performanceTimesSmall: number[] = [avgTimeSimSmall, avgTimeMathSmall];
const normalizedColorsSmall = normalizeColors(performanceTimesSmall);

const { result: avgResSimMedium, time: avgTimeSimMedium } = runPerformanceTests(
  sqeuclidean,
  vectorC_F32Arr,
  vectorD_F32Arr,
  numIterations,
);

const { result: avgResMathMedium, time: avgTimeMathMedium } =
  runPerformanceTests(euclideanDistance, vectorC, vectorD, numIterations);

const performanceTimesMedium = [avgTimeSimMedium, avgTimeMathMedium];
const normalizedColorsMedium = normalizeColors(performanceTimesMedium);

const { result: avgResSimLong, time: avgTimeSimLong } = runPerformanceTests(
  sqeuclidean,
  vectorE_F32Arr,
  vectorF_F32Arr,
  numIterations,
);

const { result: avgResMathLong, time: avgTimeMathLong } = runPerformanceTests(
  euclideanDistance,
  vectorE,
  vectorF,
  numIterations,
);
const performanceTimesLong = [avgTimeSimLong, avgTimeMathLong];
const normalizedColorsLong = normalizeColors(performanceTimesLong);
---

<SpeedTestLayout
  title="simsimd library speedup experiment"
  description="simsimd library speedup experiment"
  numIterations={numIterations}
>
  <h2 class="header">
    Perform sqeuclidean by <a href="https://github.com/ashvardanian/simsimd"
      >simsimd</a
    > or using <a
      href="https://www.30secondsofcode.org/js/s/euclidean-distance/"
    >
      traditional methods
    </a>
  </h2>
  <div class="content">
    <SimsimdRes
      size={small_size}
      normalizedColors={normalizedColorsSmall}
      avgTimeSim={avgTimeSimSmall}
      avgTimeMath={avgTimeMathSmall}
      avgResSim={avgResSimSmall}
      avgResMath={avgResMathSmall}
    />
    <hr />
    <SimsimdRes
      size={medium_size}
      normalizedColors={normalizedColorsMedium}
      avgTimeSim={avgTimeSimMedium}
      avgTimeMath={avgTimeMathMedium}
      avgResSim={avgResSimMedium}
      avgResMath={avgResMathMedium}
    />
    <hr />
    <SimsimdRes
      size={long_size}
      normalizedColors={normalizedColorsLong}
      avgTimeSim={avgTimeSimLong}
      avgTimeMath={avgTimeMathLong}
      avgResSim={avgResSimLong}
      avgResMath={avgResMathLong}
    />
  </div>
</SpeedTestLayout>

```

**Comment by FlipFloop** [comment]
You can see here: click on /experiments: https://victorguyard-392vahokg-victor-guyard-s-team.vercel.app/more/

**Comment by ashvardanian** [comment]
@FlipFloop, any chance the prebuilt packages coming in #59 would help with that?

**Comment by FlipFloop** [comment]
Possibly? I used ES6 syntax to import.. tell me when it's merged!

**Comment by ashvardanian** [comment]
@sroussey, any thoughts on this?

**Comment by sroussey** [comment]
I'll check out this afternoon. 

BTW: is this vercel edge? Or node?

Their edge uses deno I think. And won't allow native code. 

Which reminds me that I could put in a fallback of JS code in case something tries to run without native code. Obviously needs to issue a warning.

**Comment by FlipFloop** [comment]
@sroussey just a default Vercel instance. Node 18/20.

Can I contribute to the fallback stuff? I think it'd be good for me to learn how this works...

**Comment by sroussey** [comment]
I have something that deploys to vercel so I can do a test later this afternoon.

**Comment by sroussey** [comment]
I know what it is, and it was something I was going to change this weekend anyhow.

**Comment by sroussey** [comment]
Don't actually use this once this version gets updated, but you can test via using `@sroussey/simsimd` instead of `simsimd` and then get back to us with results.

**Comment by ashvardanian** [comment]
@sroussey, should I already merge the #59? Is it supposed to close this?
@FlipFloop, sure, contributions always welcome - thank you!

**Comment by sroussey** [comment]
Not yet.

**Comment by sroussey** [comment]
So, from what I can tell, you can not use native libraries on vercel.

I did fix an issue where if you are using nextjs and you want to serve on your own nodejs server you can.

[See the docs](https://vercel.com/guides/why-does-my-serverless-function-work-locally-but-not-when-deployed#native-dependencies) to read more. Edge functions are even more restricted.

**Comment by sroussey** [comment]
On failure, we could fallback I guess. The functions are simple, for example (ask @ashvardanian if correct!)

```ts
export function inner_distance(arr1: number[], arr2: number[]) {
  return 1 - arr1.reduce((acc, val, i) => acc + val * arr2[i], 0);
}
```

**Comment by ashvardanian** [comment]
Yes, @sroussey that makes sense. @FlipFloop would you be able to provide fallback implementations for other distance functions?

**Comment by FlipFloop** [comment]
Sure, however how could I check ahead of time if the fallback is needed, since the package won't build at all on those instances?

**Comment by FlipFloop** [comment]
Here is where I am at. I can't test the fallback stuff because I run into an issue where I can't import them? Also not all the functions were being tested in the first place....

https://github.com/ashvardanian/SimSIMD/compare/main...FlipFloop:SimSIMD:main

**Comment by FlipFloop** [comment]
Update: even after 3.6.5, this doesn't work.

**Comment by ashvardanian** [comment]
I am ready to review and merge if you guys have any other ideas?

**Comment by FlipFloop** [comment]
Wasn't it here?
[https://github.com/ashvardanian/SimSIMD/pull/64](https://github.com/ashvardanian/SimSIMD/pull/64)

**Comment by sroussey** [comment]
The [latest version on npm](https://www.npmjs.com/package/simsimd?activeTab=versions) is 3.6.4 not 3.6.5

**Comment by FlipFloop** [comment]
My apologies! I thought it auto published!

**Comment by sroussey** [comment]
Fixed. See https://github.com/ashvardanian/SimSIMD/pull/66
